import { Geist, Geist_Mono, Poppins, Roboto, Inter } from "next/font/google";
import "./../globals.css";
import 'leaflet/dist/leaflet.css';


import {
  ClerkProvider
} from '@clerk/nextjs'

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

const inter = Inter({
  weight: ['300', '400'],
  subsets: ['latin'],
  display: 'swap',
});



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Rural Cohort_Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${poppins.className} ${roboto.className} ${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
