import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./../globals.css";
import 'leaflet/dist/leaflet.css';
import Header from "@/components/Header/Header";
import Footer from './../../components/Footer/Footer.jsx'

import {
  ClerkProvider
} from '@clerk/nextjs'

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Rural Cohort_Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
    </ClerkProvider>
  );
}
